# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b3bf5c48-b3c6-4c1c-bdb5-6c638e1efc85'
  imageRepository: 'gwadadasolmoneymanagerdev'
  containerRegistry: 'moneymanagerregdev.azurecr.io'
  tag: '$(Build.BuildId)'
  imageName: 'gwadadasolmoneymanagertransasactionservice'
  dockerfilePath: '$(Build.SourcesDirectory)/backend/MoneyManagerBackend/TransactionService/Dockerfile'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

# stages:
# - stage: Build
  # displayName: Build
  # jobs:
  # - job: Build
  #   displayName: Build
pool:
  vmImage: $(vmImageName)
steps:
- task: Docker@2
  displayName: Build Transaction Image
  inputs:
    command: build
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    tags: |
      $(tag)
