apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzerservice
  template:
    metadata:
      labels:
        app: analyzerservice
    spec:
      containers:
        - name: analyzerservice
          image: gwadadasol/analyzerservice:latest
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db-password
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db-user---
apiVersion: v1
kind: Service
metadata: 
  name: analyzer-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: analyzerservice
  ports:
    - name: analyzerservice
      protocol: TCP
      port: 80
      targetPort: 80