name: Docker Image CI

env:
  tagId: $(date +%s)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run:
    working-directory: ./backend/MoneyManagerBackend/CategoryService

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gwadadasol/categoryservice:${{tagId}}
    - name: Push image to repository
      run: docker push gwadadasol/categoryservice:${{tagId}}
